[package]
name = "dweb"
description = "Decentralised web and storage library for Autonomi"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "dweb"
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
# Updated for autonomi 0.2.4
autonomi = { path = "../../../autonomi/autonomi/autonomi", version = "0.2.4", features = [
    "fs",
    "vault",
    "registers",
    "loud",
]}
ant-networking = { version = "0.19.0", path = "../../../autonomi/autonomi/ant-networking" }
ant-registers = { version = "0.4.0", path = "../../../autonomi/autonomi/ant-registers" }
ant-protocol = { version = "0.17.12", path = "../../../autonomi/autonomi/ant-protocol" }
ant-bootstrap = { path = "../../autonomi/ant-bootstrap", version = "0.1.0" }
ant-logging = { path = "../../autonomi/ant-logging", version = "0.2.40" }
ant-build-info = { path = "../../autonomi/ant-build-info", version = "0.1.19" }

## Everything else
http = "1.1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = { version = "~0.8.5", features = ["small_rng"] }
anyhow = "1.0.81"
async-stream = "0.3.5"
bytes = "1.6.0"
futures = "0.3.30"
indicatif = { version = "0.17.5", features = ["tokio"] }
log = "0.4.21"
multiaddr = "0.18.1"
tempfile = "3.10.1"
xor_name = "5.0.0"
color-eyre = "0.6.3"
env_logger = "0.11.3"
dirs-next = "2.0.0"
structopt = "0.3.26"
clap = "4.5.4"
walkdir = "~2.5.0"
chrono = { version = "0.4.37", features = ["serde"] }
rmp-serde = "1.1.2"
self_encryption = "0.29.1"
crdts = "7.3.2"
url = "2.5.0"
regex = "1.9.6"
ring = "0.17.8"
prettytable = "0.10.0"
const-hex = "1.13.1"
hex = "0.4.3"
rpassword = "7.3.1"
thiserror = "2.0.0"
evmlib = "0.1.4"

[features]
default = ["skip-network-compatibility-check"]
local = ["autonomi/local"]
metrics = ["ant-logging/process-metrics"]
skip-network-compatibility-check = []   # Avoid need to upload avp type and include xor address in build
