[package]
name = "dweb-cli"
description = "Decentralised web and storage command line app for Autonomi"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "dweb"
path = "src/main.rs"

[dependencies]
# autonomi = "0.2.4"
autonomi = { path = "../../autonomi/autonomi", version = "0.2.4", features = [
    "fs",
    "vault",
    "registers",
    "loud",
] }
ant-bootstrap = { path = "../../autonomi/ant-bootstrap", version = "0.1.0"  }
ant-registers = { path = "../../autonomi/ant-registers", version = "0.4.0" }

clap = "4.5.21"
color-eyre = "0.6.3"
dweb = { version = "0.0.1", path = "../dweb-lib" }
indicatif = "0.17.9"
log = "0.4.22"
regex = "1.11.1"
xor_name = "5.0.0"

[lints]
workspace = true
